### PR TITLE
Replace /home/$USER with $HOME

### PR DESCRIPTION
**Pull request by mxgic1337**
I had a problem with installing osu! because the name of my home folder is not my username. I fixed it by replacing every `/home/$USER` with `$HOME`.

### CODE REVIEW

**Comment by NelloKudo** [comment]
Some of these changes are fine, but I’m pretty sure using $HOME in a .desktop file and in Wine registry won’t work. Have you tried them already?

**Comment by mxgic1337** [comment]
Everything works fine for me.

**Comment by PhoenixEmik** [comment]
I think this change needs more testing by others.

**Comment by NelloKudo** [comment]
Sorry for sleeping on this, I'll be testing it on some setups asap. I just remember some people having issues with that when I first released the script, so I was surprised to hear it actually worked xD

Merging once I verify it works  🥳

**Pull request merged**
