### PR TITLE
Replace gosumemory with tosu linux release

### PR DESCRIPTION
**Pull request by kartavkun**

### CODE REVIEW

**Comment by NelloKudo** [comment]
Rather than using the Linux release though, which will need sudo everytime, I'd like to use the Windows executable instead. Should probably work fine anyways, but I'll need to test it xd

Also I was thinking of pulling the latest tag so that the download will always be the latest version, and add a --reinstall flag just in case. Thanks for the PR though, feel free to try what I said above as well 🥳

**Comment by kartavkun** [comment]
I'd like to have contact with you through Discord or Telegram(more better for me xdd) (at)kartav__ in discord or (at)kartavkun

**Comment by kartavkun** [comment]
Linux release need to be executed as rrot, yeah, but It works fine with umu-run

Anyway, I changed the lunux release of tosu to windows release. Tosu contains auto-updates when you execute it, so you don't need to change the release link. This is great

**Comment by kartavkun** [comment]
> Have you tested it? Is tosu launching fine?

Actually no, bc I live in dormitory and only have the old laptop with HDD(I don't have extra SSD) and I tryed to install osu-winello, but it loads too long.

But technicallly, it would work fine I guess

**Comment by Sclafus** [comment]
I think that this should be a new flag instead, it should not remove the ability to use gosumemory. Some people might prefer it.

**Comment by NelloKudo** [comment]
> I think that this should be a new flag instead, it should not remove the ability to use gosumemory. Some people might prefer it.

Totally agreed on this one.

Anyways this needs some more work done as the current implementation of Gosumemory relies on system libraries and with Proton we really don't want that. I still haven't managed to make it work with umu-run but I'm working on it 👍🏻

**Comment by kartavkun** [comment]
Main problem is gosumemory is abadonded project. Latest release was in [18 December 2023](https://github.com/l3lackShark/gosumemory/releases/tag/1.3.9) and released by @cyperdark and @KotRikD
And now they're develop [tosu](https://github.com/KotRikD/tosu)
Tosu is better bc of user-friendly and obviously better UI. It also not abadoned like gosumemory, so tosu would be better

**Comment by Sclafus** [comment]
> Main problem is gosumemory is abadonded project. Latest release was in 18 December 2023 [...]

To be fair, stable does not receive many updates, so there is no big need for updating stuff. 
The main issue is that tosu has a different output in the websocket. Other projects/programs may depend on it, and it may break some usecases for some users (like me!!!!)
If gosumemory becomes _officially_ deprecated, it would make sense to remove it, agreed. I don't see any harm in leaving it in the script for the time being.

**Comment by KotRikD** [comment]
tosu don't need root to run. At first, we thought to do everything via root, but it turned out that some linux builds don't require it (maybe there was some configured access to `/proc`). So we removed the root requirement, and just write to the console, if we can't open the process (maybe author should add a flag `--run-tosu-via-sudo` to script).

**Comment by kartavkun** [comment]
> To be fair, stable does not receive many updates, so there is no big need for updating stuff. 

Debian moment

> The main issue is that tosu has a different output in the websocket. Other projects/programs may depend on it, and it may break some usecases for some users (like me!!!!)

What are the use cases? Are there other use cases for overlay output? Let's be more specific, without abstractions. it sounds just crazy

**Comment by kartavkun** [comment]
> tosu don't need root to run

wha? How tosu would read the osu memory then?
Maybe Arch Linux need sudo/doas or I am a retard, but it wouldn't work properly as user

**Comment by cyperdark** [comment]
> The main issue is that tosu has a different output in the websocket.

/ws is gosu like output, may I ask what is different there?

**Comment by KotRikD** [comment]
> > tosu don't need root to run
> 
> wha? How tosu would read the osu memory then? Maybe Arch Linux need sudo/doas or I am a retard, but it wouldn't work properly as user

https://github.com/KotRikD/tosu/issues/174#issuecomment-2262821004

**Comment by KotRikD** [comment]
> > Main problem is gosumemory is abadonded project. Latest release was in 18 December 2023 [...]
> 
> To be fair, stable does not receive many updates, so there is no big need for updating stuff...
Stable updates can break memory points, some points are already broken in gosumemory, and I won't fix them more.

> The main issue is that tosu has a different output in the websocket. Other projects/programs may depend on it, and it may break some usecases for some users (like me!!!!) 

tosu API is have backwards compatible with gosumemory (/ws, /json routes), please read wiki or provide more context, we will be glad to help

> If gosumemory becomes _officially_ deprecated, it would make sense to remove it, agreed. I don't see any harm in leaving it in the script for the time being.

Partialy, it's already become _officially_ deprecated, check announcment channel in official gosu discord...

**Comment by kartavkun** [comment]
> > > tosu don't need root to run
> > 
> > 
> > wha? How tosu would read the osu memory then? Maybe Arch Linux need sudo/doas or I am a retard, but it wouldn't work properly as user
> 
> [KotRikD/tosu#174 (comment)](https://github.com/KotRikD/tosu/issues/174#issuecomment-2262821004)

 Okay, I get it
 
image

**Comment by Sclafus** [comment]
> Partialy, it's already become _officially_ deprecated, check announcment channel in official gosu discord...

Sorry, but this sounds weird. Why should I join a Discord server to have the opportunity of knowing that gosumemory is getting deprecated, while there is no mention of it in the repo? Shouldn't there be a notice saying "hey btw use tosu instead of gosumemory, this will not be updated anymore"? 

> /ws is gosu like output, may I ask what is different there?

I simply did not test it yet. I just assumed it was different, should have phrased it better. Usually when projects are fully compatible with other projects, they say so explicitly. My bad, happy to be wrong!

**Comment by cyperdark** [comment]
> Usually when projects are fully compatible with other projects, they say so explicitly

Not explicit but says in readme

**Comment by cyperdark** [comment]
> while there is no mention of it in the repo? Shouldn't there be a notice saying "hey btw use tosu instead of gosumemory, this will not be updated anymore"?

Ask blackshark why he decided to post it only in discord. I'm not editing repo readme without his permissions, but he's being unreachable for 8 months now, so you can't get any message from him

**Comment by kartavkun** [comment]
> Shouldn't there be a notice saying "hey btw use tosu instead of gosumemory, this will not be updated anymore"?

Just check BlackShark's activity on Github lol

image

That's 2024, and no gosumemory

image

In 2023 the only one commit in gosumemory and about PR xdd

Just do any fact checking. No offence bro

**Comment by kartavkun** [comment]
> No offence bro

**Comment by Sclafus** [comment]
> Just do any fact checking. No offence bro

As I said, I am happy to be wrong. Feel free to remove the gosumemory option. No need for snarky comments.

**Comment by kartavkun** [comment]
> As I said, I am happy to be wrong. Feel free to remove the gosumemory option. No need for snarky comments.

 Text in Ryan Gosling gif means: "without any negative"
 I wrote that without any negativity or anything like that

**Review by Sclafus — CHANGES_REQUESTED** [review]
Since we are removing completely the ability to use gosumemory, might as well remove the other mentions as well:
https://github.com/kartavkun/osu-winello/blob/main/osu-winello.sh#L513-L523

https://github.com/kartavkun/osu-winello/blob/main/osu-winello.sh#L567-L569

https://github.com/kartavkun/osu-winello/blob/main/osu-wine#L59

**Comment by NelloKudo** [comment]
> tosu don't need root to run. At first, we thought to do everything via root, but it turned out that some linux builds don't require it (maybe there was some configured access to `/proc`). So we removed the root requirement, and just write to the console, if we can't open the process (maybe author should add a flag `--run-tosu-via-sudo` to script).

Thanks for the heads-up, then I'll use it if I can't manage to make the Windows executable work. 👍🏻 

> As I said, I am happy to be wrong. Feel free to remove the gosumemory option. No need for snarky comments.

Agreed, thanks for the clarification on gosumemory's situation but as a casual user of it myself, it's only natural to think that *adding a new option* is better than *replacing* it. As someone who needs to provides utils working for anyone, I'll probably keep gosumemory under a `--legacy-gosumemory` flag and promote `tosu` as the better program to use right now.
Congrats on the great work on tosu though, works like a charm from my experience.

As for @kartavkun, the PR still has some issues but I'll need to work on it myself before merging or reviewing, there's more I want to look into and I'd like to avoid using the Linux release as I'll need to implement a `--sudo` flag myself like we mentioned before in the worst use-case. Thanks for your time everyone!

**Comment by kartavkun** [comment]
> Since we are removing completely the ability to use gosumemory, might as well remove the other mentions as well: https://github.com/kartavkun/osu-winello/blob/main/osu-winello.sh#L513-L523
> 
> https://github.com/kartavkun/osu-winello/blob/main/osu-winello.sh#L567-L569
> 
> https://github.com/kartavkun/osu-winello/blob/main/osu-wine#L59

 I tried to revert commits, but I'm bad at CLI Git. Unlucky xdd

**Comment by NelloKudo** [comment]
tosu is now implemented with https://github.com/NelloKudo/osu-winello/commit/f6716c95f5a02954bce1717383705e96b20b51db! 

Thanks for the PR and the help but this needed some more work to launch properly. Let me know if any issues come up!

**Pull request closed without merging**
